-- Create designs table
create table designs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  image_url text not null,
  public_url text not null,
  prompt text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  text1 text,
  text2 text,
  font1 text,
  font2 text,
  color1 text,
  color2 text,
  size1 integer,
  size2 integer
);

-- Enable Row Level Security
alter table designs enable row level security;

-- Create policies for designs table
create policy "Users can view their own designs"
on designs for select
using (auth.uid() = user_id);

create policy "Users can insert their own designs" 
on designs for insert
with check (auth.uid() = user_id);

create policy "Users can update their own designs"
on designs for update
using (auth.uid() = user_id);

create policy "Users can delete their own designs"
on designs for delete
using (auth.uid() = user_id);

-- Create index for faster user-specific queries
create index idx_designs_user_id on designs (user_id);

-- Create trigger to automatically update updated_at timestamp
create extension if not exists moddatetime;

create trigger handle_updated_at before update on designs
  for each row execute procedure moddatetime (updated_at);
